"""Self-aware modules for 108 Vedic Astrology system.

Specialized analysis modules:
- Yoga detection (Raja, Dhana, Pancha Mahapurusha, etc.)
- Dosha detection and remedies
- Advanced chart interpretations
"""

from .ashtakavarga import (
    calculate_bhinnashtakavarga,
    calculate_sarvashtakavarga,
    get_transit_ashtakavarga_analysis,
    get_transit_ashtakavarga_score,
    get_transit_strength_modifier,
    interpret_ashtakavarga_score,
)
from .chandra_kala_nadi import (
    get_ckn_reading,
    get_conjunctions,
    get_planet_sign_map,
)
from .combustion import (
    check_combustion,
    check_combustion_cancellation,
    get_combustion_analysis,
    get_combustion_house_effects,
)
from .compatibility import (
    calculate_ashta_kuta,
    calculate_bhakoot_score,
    calculate_gana_score,
    calculate_graha_maitri_score,
    calculate_nadi_score,
    calculate_tara_score,
    calculate_varna_score,
    calculate_vashya_score,
    calculate_yoni_score,
    get_compatibility_verdict,
)
from .divisional_interpreter import (
    get_divisional_analysis,
    interpret_d2_position,
    interpret_d3_position,
    interpret_d4_position,
    interpret_d7_position,
    interpret_d9_chart,
    interpret_d9_position,
    interpret_d10_chart,
    interpret_d10_position,
    interpret_d12_position,
    interpret_d16_position,
    interpret_d20_position,
    interpret_d24_position,
    interpret_d27_position,
    interpret_d30_position,
    interpret_d60_position,
)
from .dosha_detector import DoshaDetector
from .gem_recommender import (
    check_gem_compatibility,
    get_lagna_gem_map,
    recommend_gems,
)
from .jaimini import (
    calculate_all_arudha_padas,
    calculate_argala,
    calculate_arudha_pada,
    calculate_chara_dasha,
    calculate_chara_karakas,
    get_all_chara_karaka_analysis,
    get_atmakaraka_analysis,
    get_ishta_devata,
    get_jaimini_aspects,
    get_karakamsha,
    get_sign_mobility,
    interpret_upapada,
)
from .karakamsha import (
    analyze_karakamsha,
    get_atmakaraka,
    get_karakamsha_lagna,
)
from .kp import (
    analyze_kp_house,
    get_cuspal_sublords,
    get_kp_prediction,
    get_kp_significators,
    get_kp_sublord,
    get_kp_sublord_table,
    get_ruling_planets,
)
from .nadi_amsha_interpreter import (
    calculate_nadi_amsha_position,
    get_nadi_amsha_chart,
)
from .numerology import (
    NUMBER_PLANET_MAP,
    LoShuGrid,
    NameAnalysis,
    NumberCompatibility,
    NumerologyProfile,
    PersonalCycles,
    calculate_destiny_number,
    calculate_full_profile,
    calculate_lo_shu_grid,
    calculate_name_number,
    calculate_personal_day,
    calculate_personal_month,
    calculate_personal_year,
    calculate_psychic_number,
    cross_reference_jyotish,
    get_number_compatibility,
)
from .planetary_war import (
    detect_planetary_wars,
    get_war_effects,
)
from .prashna import (
    analyze_health_prashna,
    analyze_legal_prashna,
    analyze_lost_object_prashna,
    analyze_marriage_prashna,
    analyze_prashna,
    analyze_travel_prashna,
    create_prashna_chart,
    get_prashna_divisional_analysis,
    get_significator,
    judge_prashna,
    predict_timing,
)
from .remedies import (
    get_planet_remedies,
    prioritize_remedies,
    recommend_remedies,
)
from .retrograde import (
    get_retrograde_analysis,
    get_retrograde_effects,
)
from .sensitive_points import (
    calculate_bhrigu_bindu,
    calculate_indu_lagna,
    calculate_sree_lagna,
    get_all_sensitive_points,
)
from .strength import StrengthCalculator
from .sudarshana_chakra import (
    analyze_house_from_three_wheels,
    get_sudarshana_chakra,
)
from .synastry import (
    calculate_composite_chart,
    calculate_cross_aspects,
    calculate_house_overlay,
    get_synastry_report,
)
from .transit_lordship import (
    analyze_transit_lordships,
    classify_planet_role,
    get_all_house_lords,
    get_lordship_summary,
    get_planet_lordships,
)
from .yoga_activation import (
    extract_yoga_houses,
    get_active_yogas,
)
from .yoga_cancellation import (
    apply_cancellations_to_chart,
    check_yoga_cancellation,
    get_cancellation_rules,
)
from .yoga_detector import (
    YogaDetector,
    detect_all_yogas,
    detect_neecha_bhanga,
    detect_yoga,
    evaluate_condition,
    get_yoga_strength,
)

__all__ = [
    "NUMBER_PLANET_MAP",
    "DoshaDetector",
    "LoShuGrid",
    "NameAnalysis",
    "NumberCompatibility",
    "NumerologyProfile",
    "PersonalCycles",
    "StrengthCalculator",
    "YogaDetector",
    "analyze_health_prashna",
    "analyze_house_from_three_wheels",
    "analyze_karakamsha",
    "analyze_kp_house",
    "analyze_legal_prashna",
    "analyze_lost_object_prashna",
    "analyze_marriage_prashna",
    "analyze_prashna",
    "analyze_transit_lordships",
    "analyze_travel_prashna",
    "apply_cancellations_to_chart",
    "calculate_all_arudha_padas",
    "calculate_argala",
    "calculate_arudha_pada",
    "calculate_ashta_kuta",
    "calculate_bhakoot_score",
    "calculate_bhinnashtakavarga",
    "calculate_bhrigu_bindu",
    "calculate_chara_dasha",
    "calculate_chara_karakas",
    "calculate_composite_chart",
    "calculate_cross_aspects",
    "calculate_destiny_number",
    "calculate_full_profile",
    "calculate_gana_score",
    "calculate_graha_maitri_score",
    "calculate_house_overlay",
    "calculate_indu_lagna",
    "calculate_lo_shu_grid",
    "calculate_nadi_amsha_position",
    "calculate_nadi_score",
    "calculate_name_number",
    "calculate_personal_day",
    "calculate_personal_month",
    "calculate_personal_year",
    "calculate_psychic_number",
    "calculate_sarvashtakavarga",
    "calculate_sree_lagna",
    "calculate_tara_score",
    "calculate_varna_score",
    "calculate_vashya_score",
    "calculate_yoni_score",
    "check_combustion",
    "check_combustion_cancellation",
    "check_gem_compatibility",
    "check_yoga_cancellation",
    "classify_planet_role",
    "create_prashna_chart",
    "cross_reference_jyotish",
    "detect_all_yogas",
    "detect_neecha_bhanga",
    "detect_planetary_wars",
    "detect_yoga",
    "evaluate_condition",
    "extract_yoga_houses",
    "get_active_yogas",
    "get_all_chara_karaka_analysis",
    "get_all_house_lords",
    "get_all_sensitive_points",
    "get_atmakaraka",
    "get_atmakaraka_analysis",
    "get_cancellation_rules",
    "get_ckn_reading",
    "get_combustion_analysis",
    "get_combustion_house_effects",
    "get_compatibility_verdict",
    "get_conjunctions",
    "get_cuspal_sublords",
    "get_divisional_analysis",
    "get_ishta_devata",
    "get_jaimini_aspects",
    "get_karakamsha",
    "get_karakamsha_lagna",
    "get_kp_prediction",
    "get_kp_significators",
    "get_kp_sublord",
    "get_kp_sublord_table",
    "get_lagna_gem_map",
    "get_lordship_summary",
    "get_nadi_amsha_chart",
    "get_number_compatibility",
    "get_planet_lordships",
    "get_planet_remedies",
    "get_planet_sign_map",
    "get_prashna_divisional_analysis",
    "get_retrograde_analysis",
    "get_retrograde_effects",
    "get_ruling_planets",
    "get_sign_mobility",
    "get_significator",
    "get_sudarshana_chakra",
    "get_synastry_report",
    "get_transit_ashtakavarga_analysis",
    "get_transit_ashtakavarga_score",
    "get_transit_strength_modifier",
    "get_war_effects",
    "get_yoga_strength",
    "interpret_ashtakavarga_score",
    "interpret_d2_position",
    "interpret_d3_position",
    "interpret_d4_position",
    "interpret_d7_position",
    "interpret_d9_chart",
    "interpret_d9_position",
    "interpret_d10_chart",
    "interpret_d10_position",
    "interpret_d12_position",
    "interpret_d16_position",
    "interpret_d20_position",
    "interpret_d24_position",
    "interpret_d27_position",
    "interpret_d30_position",
    "interpret_d60_position",
    "interpret_upapada",
    "judge_prashna",
    "predict_timing",
    "prioritize_remedies",
    "recommend_gems",
    "recommend_remedies",
]
