"""Self-aware modules for 108 Vedic Astrology system.

Specialized analysis modules:
- Yoga detection (Raja, Dhana, Pancha Mahapurusha, etc.)
- Dosha detection and remedies
- Advanced chart interpretations
"""

from .ashtakavarga import (
    calculate_bhinnashtakavarga,
    calculate_sarvashtakavarga,
    get_transit_ashtakavarga_analysis,
    get_transit_ashtakavarga_score,
    get_transit_strength_modifier,
    interpret_ashtakavarga_score,
)
from .combustion import (
    check_combustion,
    check_combustion_cancellation,
    get_combustion_analysis,
    get_combustion_house_effects,
)
from .compatibility import (
    calculate_ashta_kuta,
    calculate_bhakoot_score,
    calculate_gana_score,
    calculate_graha_maitri_score,
    calculate_nadi_score,
    calculate_tara_score,
    calculate_varna_score,
    calculate_vashya_score,
    calculate_yoni_score,
    get_compatibility_verdict,
)
from .divisional_interpreter import (
    get_divisional_analysis,
    interpret_d2_position,
    interpret_d3_position,
    interpret_d4_position,
    interpret_d7_position,
    interpret_d9_chart,
    interpret_d9_position,
    interpret_d10_chart,
    interpret_d10_position,
    interpret_d12_position,
    interpret_d16_position,
    interpret_d20_position,
    interpret_d24_position,
    interpret_d27_position,
    interpret_d30_position,
    interpret_d60_position,
)
from .dosha_detector import DoshaDetector
from .gem_recommender import (
    check_gem_compatibility,
    get_lagna_gem_map,
    recommend_gems,
)
from .jaimini import (
    calculate_all_arudha_padas,
    calculate_argala,
    calculate_arudha_pada,
    calculate_chara_dasha,
    calculate_chara_karakas,
    get_all_chara_karaka_analysis,
    get_atmakaraka,
    get_atmakaraka_analysis,
    get_ishta_devata,
    get_jaimini_aspects,
    get_karakamsha,
    get_sign_mobility,
    interpret_upapada,
)
from .planetary_war import (
    detect_planetary_wars,
    get_war_effects,
)
from .prashna import (
    analyze_health_prashna,
    analyze_legal_prashna,
    analyze_lost_object_prashna,
    analyze_marriage_prashna,
    analyze_prashna,
    analyze_travel_prashna,
    create_prashna_chart,
    get_prashna_divisional_analysis,
    get_significator,
    judge_prashna,
    predict_timing,
)
from .remedies import (
    get_planet_remedies,
    prioritize_remedies,
    recommend_remedies,
)
from .retrograde import (
    get_retrograde_analysis,
    get_retrograde_effects,
)
from .strength import StrengthCalculator
from .synastry import (
    calculate_composite_chart,
    calculate_cross_aspects,
    calculate_house_overlay,
    get_synastry_report,
)
from .yoga_cancellation import (
    apply_cancellations_to_chart,
    check_yoga_cancellation,
    get_cancellation_rules,
)
from .yoga_detector import (
    YogaDetector,
    detect_all_yogas,
    detect_neecha_bhanga,
    detect_yoga,
    evaluate_condition,
    get_yoga_strength,
)

__all__ = [
    "DoshaDetector",
    "StrengthCalculator",
    "YogaDetector",
    "analyze_health_prashna",
    "analyze_legal_prashna",
    "analyze_lost_object_prashna",
    "analyze_marriage_prashna",
    "analyze_prashna",
    "analyze_travel_prashna",
    "apply_cancellations_to_chart",
    "calculate_all_arudha_padas",
    "calculate_argala",
    "calculate_arudha_pada",
    "calculate_ashta_kuta",
    "calculate_bhakoot_score",
    "calculate_bhinnashtakavarga",
    "calculate_chara_dasha",
    "calculate_chara_karakas",
    "calculate_composite_chart",
    "calculate_cross_aspects",
    "calculate_gana_score",
    "calculate_graha_maitri_score",
    "calculate_house_overlay",
    "calculate_nadi_score",
    "calculate_sarvashtakavarga",
    "calculate_tara_score",
    "calculate_varna_score",
    "calculate_vashya_score",
    "calculate_yoni_score",
    "check_combustion",
    "check_combustion_cancellation",
    "check_gem_compatibility",
    "check_yoga_cancellation",
    "create_prashna_chart",
    "detect_all_yogas",
    "detect_neecha_bhanga",
    "detect_planetary_wars",
    "detect_yoga",
    "evaluate_condition",
    "get_all_chara_karaka_analysis",
    "get_atmakaraka",
    "get_atmakaraka_analysis",
    "get_cancellation_rules",
    "get_combustion_analysis",
    "get_combustion_house_effects",
    "get_compatibility_verdict",
    "get_divisional_analysis",
    "get_ishta_devata",
    "get_jaimini_aspects",
    "get_karakamsha",
    "get_lagna_gem_map",
    "get_planet_remedies",
    "get_prashna_divisional_analysis",
    "get_retrograde_analysis",
    "get_retrograde_effects",
    "get_sign_mobility",
    "get_significator",
    "get_synastry_report",
    "get_transit_ashtakavarga_analysis",
    "get_transit_ashtakavarga_score",
    "get_transit_strength_modifier",
    "get_war_effects",
    "get_yoga_strength",
    "interpret_ashtakavarga_score",
    "interpret_d2_position",
    "interpret_d3_position",
    "interpret_d4_position",
    "interpret_d7_position",
    "interpret_d9_chart",
    "interpret_d9_position",
    "interpret_d10_chart",
    "interpret_d10_position",
    "interpret_d12_position",
    "interpret_d16_position",
    "interpret_d20_position",
    "interpret_d24_position",
    "interpret_d27_position",
    "interpret_d30_position",
    "interpret_d60_position",
    "interpret_upapada",
    "judge_prashna",
    "predict_timing",
    "prioritize_remedies",
    "recommend_gems",
    "recommend_remedies",
]
