"""108 core package - shared types, models, and utilities for Vedic astrology."""
from .constants import (
    DASHA_SEQUENCE,
    DASHA_YEARS,
    NAKSHATRA_SPAN,
    PADA_SPAN,
    TOTAL_DASHA_YEARS,
    AyanamsaType,
    Gana,
    HouseCategory,
    HouseSystem,
    Planet,
    Rashi,
    YogaCategory,
)
from .knowledge_loader import (
    clear_cache as clear_knowledge_cache,
)
from .knowledge_loader import (
    get_ashtakavarga_rules,
    get_aspects,
    get_compatibility_rules,
    get_dasha_rules,
    get_dignities,
    get_dosha_rules,
    get_houses,
    get_muhurta_rules,
    get_nakshatras,
    get_planets,
    get_rashis,
    get_relationships,
    get_remedies,
    get_shadbala_rules,
    get_transit_rules,
    get_yoga_rules,
    load_definition,
    load_rules,
)
from .models import (
    BirthChart,
    BirthData,
    CurrentDasha,
    DashaPeriod,
    DetectedDosha,
    DetectedYoga,
    HouseCusps,
    NakshatraInfo,
    Panchanga,
    PlanetPosition,
    TransitPosition,
    UserProfile,
)
from .utils import (
    calculate_aspect_houses,
    get_house_from_signs,
    get_opposite_sign,
    is_dusthana,
    is_kendra,
    is_trikona,
    is_upachaya,
    longitude_to_nakshatra,
    longitude_to_rashi,
    normalize_degrees,
)

__all__ = [
    "DASHA_SEQUENCE",
    "DASHA_YEARS",
    "NAKSHATRA_SPAN",
    "PADA_SPAN",
    "TOTAL_DASHA_YEARS",
    "AyanamsaType",
    "BirthChart",
    # Pydantic Models
    "BirthData",
    "CurrentDasha",
    "DashaPeriod",
    "DetectedDosha",
    "DetectedYoga",
    "Gana",
    "HouseCategory",
    "HouseCusps",
    "HouseSystem",
    "NakshatraInfo",
    "Panchanga",
    # Constants and Enums
    "Planet",
    "PlanetPosition",
    "Rashi",
    "TransitPosition",
    "UserProfile",
    "YogaCategory",
    "calculate_aspect_houses",
    "clear_knowledge_cache",
    "get_ashtakavarga_rules",
    "get_aspects",
    "get_compatibility_rules",
    "get_dasha_rules",
    "get_dignities",
    "get_dosha_rules",
    "get_house_from_signs",
    "get_houses",
    "get_muhurta_rules",
    "get_nakshatras",
    "get_opposite_sign",
    "get_planets",
    "get_rashis",
    "get_relationships",
    "get_remedies",
    "get_shadbala_rules",
    "get_transit_rules",
    "get_yoga_rules",
    "is_dusthana",
    "is_kendra",
    "is_trikona",
    "is_upachaya",
    # Knowledge Loaders
    "load_definition",
    "load_rules",
    "longitude_to_nakshatra",
    "longitude_to_rashi",
    # Utility Functions
    "normalize_degrees",
]
