import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:one_zero_eight/data/models/chat_message_model.dart';
import 'package:one_zero_eight/data/services/api_service.dart';
import 'package:one_zero_eight/core/constants/api_constants.dart';

part 'chat_provider.g.dart';

/// State notifier for chat messages
class ChatMessagesNotifier extends StateNotifier<List<ChatMessageModel>> {
  ChatMessagesNotifier() : super([]);

  void addMessage(ChatMessageModel message) {
    state = [...state, message];
  }

  void replaceLastMessage(ChatMessageModel message) {
    if (state.isNotEmpty) {
      final newState = [...state];
      newState[newState.length - 1] = message;
      state = newState;
    }
  }

  void clearMessages() {
    state = [];
  }
}

/// Chat messages provider (manual — StateNotifierProvider is not generated by riverpod_annotation)
final chatMessagesProvider =
    StateNotifierProvider.autoDispose<ChatMessagesNotifier, List<ChatMessageModel>>(
  (ref) => ChatMessagesNotifier(),
);

/// Get remaining messages today
@riverpod
Future<int> remainingMessages(RemainingMessagesRef ref) async {
  final response = await ApiService().get(
    ApiConstants.chatRemaining,
    fromJson: (json) => json['remaining'] as int,
  );
  return response;
}

/// Send chat message
@riverpod
class SendChatMessage extends _$SendChatMessage {
  @override
  FutureOr<void> build() {
    // Void provider
  }

  Future<void> call(String message) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      try {
        // Add user message to state
        ref.read(chatMessagesProvider.notifier).addMessage(
          ChatMessageModel(
            id: DateTime.now().toString(),
            userId: '', // Will be filled by API
            role: 'user',
            content: message,
            contentType: 'text',
            metadata: {},
            blocks: [],
            tokensUsed: 0,
            createdAt: DateTime.now(),
          ),
        );

        // Send to API
        final response = await ApiService().post(
          ApiConstants.chat,
          body: {'message': message},
          fromJson: (json) => ChatMessageModel.fromJson(json['message']),
        );

        // Add assistant response
        ref.read(chatMessagesProvider.notifier).addMessage(response);

        // Refresh remaining count
        ref.invalidate(remainingMessagesProvider);
      } catch (e) {
        print('Failed to send message: $e');
        rethrow;
      }
    });
  }
}

/// Load chat history
@riverpod
Future<List<ChatMessageModel>> chatHistory(ChatHistoryRef ref, {
  int limit = 50,
  int offset = 0,
}) async {
  final response = await ApiService().get(
    '${ApiConstants.chatHistory}?limit=$limit&offset=$offset',
    fromJson: (json) => (json['messages'] as List)
        .map((m) => ChatMessageModel.fromJson(m))
        .toList(),
  );
  return response;
}
